### ISSUE TITLE
Need to add plugin to https://hapijs.com/plugins

### ISSUE THREAD

**Issue by alberttwong** [nodearch/arch#2]
and remove hapi-arch

**Comment by AhmedAli7O1** [comment]
thanks for your input, hapi-arch will be deprecated, but currently I have in development a new version of the hapi-arch generator for nodearch, once it's finished I will add it instead to hapijs.com, because I can't add nodearch itself, because it's more of a microservices tool kit that could be used with any web framework e.g hapi.js, express, koa...etc
