### ISSUE TITLE
Problem with a Service calling another Service

### ISSUE THREAD

**Issue by alberttwong** [nodearch/arch#5]
I'm having a problem with this code.   This would seem like it's simple but I think nodearch is causing more complexity.

```
'use strict';

const { models } = require('nodearch').deps.trust;

const { Trust } = models;

const { services } = require('nodearch').deps.questionEntry;

const { QuestionEntryService } = services;

const { QuestionEntry } = models;



module.exports = {

  yourreview: (criteria) => {

    // params: me, you

    /**
      * Get all Question Entries for yourself
      * Loop until find the you in the votee and get the result (0,1)
      * 
    */

    /**
     * This doesn't work.   
     */
     var results = QuestionEntryService.find( criteria );
     while(results.hasNext()) {
       result = results.next();
       console.log(result);
     }
     
    /**
     * Trying another method.   Maybe the problem is that I'm using criteria and it's a different object type.
     * var something = new QuestionEntry({voter:criteria.me, votee:criteria.you});
     */
    var results = QuestionEntryService.find( QuestionEntry({voter:criteria.me, votee:criteria.you}), function (something) {Console.log(something) } );

  },

  otherreview: (criteria) => {

    /**
    * Get all the ID of people you trust and they trust you
    * Loop using person you trust and if they trust "you"
    *       Save all yes
    *       Save all no
    *       Save total.  eg 3 of 5 say yes.   1 of 5 say no.
    * Return "your network trust this person" or "your network doesn't trust this person"

     */

    return Trust
      .find(criteria);
  }
};
```

**Comment by AhmedAli7O1** [comment]
Hello @alberttwong 

thanks for your feedback, and let me explain a couple of points.

nodearch is a an upgraded version of hapi-arch that was meant to allow the developer to use extend or even change the project structure as needed while still keeping all the feature of this microservices kit, for example the reason you can't just require your modules directly and instead you access it via `require("nodearch").deps` is that modules loading is all taking care of by nodearch, and the main reason for this, is to give the developer full control over the server initialization life cycle using nodearch extensions, as documented here: https://github.com/nodearch/arch#extensions extensions is not meant to be used in business related code, instead it should be for fulfilling your technical needs, for example you can write a Message Broker client that support multiple Message Brokers and share with your team, so everyone would just need to install the extension.

so with nodearch handling the dependencies in your case, it seems that you're trying to access a service in another plugin, here is the thing, you have to make sure that the service you're trying to access is already loaded before the service that you're accessing from, this is just simple ordering, if you have the following files:
```
one.js
two.js
```

and you're going to call `one.find` from `two.js` file then you have to put them in the right order in the file `spec.json` inside your plugin which is as follows:
```json
[
  {
    "name": "one.js",
    "type": "module"
  },
  {
    "name": "two.js",
    "type": "module"
  }
]
``` 
but what if the `one.js` file in in another plugin, so you have
```
pluginX/one.js
pluginY/two.js
``` 
that means you have the `pluginX` as a dependency to `pluginY` you can order plugins as well from the `spec.json` file in the `api` directory.

```
[
  {
    "name": "questionEntry"
  }
]
```

the complexity here will raise if your code got a lot of dependencies which is an indicator that you should stop and think about refactoring your code. 


does this means you need to add every file to `spec.json`? the answer is NO you only need to add all files/folders in which you need to make sure to load first then everything else will be loaded automaticlly after this. here is a couple of examples:

in the plugins ordering file `/api/spec.json` if you put this:
```json
[
  {
    "name": "questionEntry"
  }
]
```

this means you're telling nodearch to load the whole `questionEntry` and then load everything else after that.

in the plugin ordering file `/api/questionEntry/spec.json` if you put this:

```
[
  {
    "name": "models",
    "type": "component"
  },
  {
    "name": "services",
    "type": "component",
    "modules": [
      { "name": "UserService.js" }
    ]
  },
  {
    "name": "controllers",
    "type": "component"
  },
  {
    "name": "schema",
    "type": "component"
  },
  {
    "name": "routes.js",
    "type": "module"
  },
  {
    "name": "test",
    "type": "component",
    "disable": true
  }
]
```

this means the following in order:
* load all models.
* load `UserService.js` then load the rest of the services ( in case this service is dependency for the other services  )
* load all controllers.
* load all schema content.
* load the file routes.js
* DO NOT LOAD the test folder. ( because this will be handled via nodearch-mocha extension  )
* load everything else in the `/api` directory. 


of course if you added more directories or files you can customize your app flow via those spec.json files and you can always change the default file structure that you got from the nodearch generator.

also I'm already working working on version 2x of nodearch which is going to be more easier to configure and there will be a single spec.json file for the whole project, and syntax is going to be easier.
